command: [
  "streamlit",
  "run",
  "app.py"
]

env:
  - name: DATABRICKS_HOST
    value: 'https://dbc-5a0c96b5-45c7.cloud.databricks.com'
  - name: VECTOR_SEARCH_ENDPOINT
    value: 'document_vector_endpoint'
  - name: INDEX_NAME
    value: 'document_catalog.default.document_index'
  - name: EMBEDDING_ENDPOINT
    value: 'databricks-bge-large-en'
  - name: LLM_ENDPOINT
    value: 'databricks-meta-llama-3-1-8b-instruct'
  - name: DATABRICKS_CLIENT_ID
    value: '9e84e630-02bb-4f17-a27f-bbae383b8761'
  - name: DATABRICKS_CLIENT_SECRET
    value: 'dose6e2133ef2c267d51524c34254881e4cb'