command: [
  "streamlit",
  "run",
  "app.py"
]

env:
  - name: DATABRICKS_HOST
    value: 'https://dbc-5a0c96b5-45c7.cloud.databricks.com'
  - name: VECTOR_SEARCH_ENDPOINT
    value: 'document_vector_endpoint'
  - name: INDEX_NAME
    value: 'document_catalog.default.document_index'
  - name: EMBEDDING_ENDPOINT
    value: 'databricks-bge-large-en'
  - name: LLM_ENDPOINT
    value: 'databricks-meta-llama-3-1-8b-instruct'